### ISSUE TITLE
Events on ion-input & ion-textarea

### ISSUE THREAD

**Issue by arcaweb** [ModusCreateOrg/ionic-vue#80]
Hi,

Ionic is creating and input / textarea inside a ion-input or ion-textarea tag, so it is impossible to use events, v-model, ... on these tags.

How can we do working this ?

Thanks

**Comment by michaeltintiuc** [comment]
Hey @arcaweb, thanks for your question. Yes, this is expected behaviour as it's quite impossible to get it working without redefining every ionic element in vue .
In essence `v-modal` is just a shorthand for `:value="myVar" @input="myVar = $event.target.value"`

As an example, you can have a look at what we did in [Beep](https://github.com/ModusCreateOrg/beep)

```vue
            <ion-input
              :type="pwdType"
              :value="pwd"
              large
              placeholder="••••••"
              @input="pwd = $event.target.value"
              @keydown.enter="checkHash"
            />
```

In case if this is a pain, you can always create a custom vue component like `my-input` which would be a wrapper for `ion-input` that way you write the long version only once and use `v-model` everywhere else.

**Comment by arcaweb** [comment]
@michaeltintiuc Thanks you for your quick answer, it's my bad, I had try with @input, but I had forgotten :value ... with :value it works well :)
