### ISSUE TITLE
:class on ion-item overwrites classNames

### ISSUE THREAD

**Issue by zwacky** [ModusCreateOrg/ionic-vue#86]
When I try to dynamically setting classes on an `<ion-item>` the classes will overwrite the native ion-item classes, disappearing the visibility and only leaves the classes defined in `:class`.
I also checked with @ionic/angular doing the same just with `[ngClass]` and there is no problem.

I used ionic-vue-example to demonstrate it in the Home component: https://github.com/zwacky/ionic-vue-examples/tree/bug/ion-item-class

Cheers!

**Comment by michaeltintiuc** [comment]
Thanks for the issue report. This is a weird one, so it works in Angular because each ionic component has a framework wrapper around it. In Vue we don't, we're just using the ones coming from @ionic/core.

So essentially what you're doing is overwriting the classes instead of appending to them.
To me it seems more like a core Vue issues where it should've checked for existing values when parsing the :class directive.

Anyhow, I believe there is a discussion about creating wrapper for the ionic/vue as well, which should be beneficial for such cases.

**Comment by michaeltintiuc** [comment]
Should be fixed by this commit: https://github.com/ionic-team/ionic/commit/4a0de23cab6c80706775ad5b6e1abb835105f5ee
